services:

  mysql:
    image: mysql:8.0
    container_name: registration-mysql

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: registration_db
      MYSQL_USER: registration_user
      MYSQL_PASSWORD: registration_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: